version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g aws-sam-cli
  pre_build:
    commands:
      - cd lambda
      - npm install
      - npm run build
      - cd ..
  build:
    commands:
      - sam build
      - sam package \
          --s3-bucket $ARTIFACT_BUCKET \
          --output-template-file packaged.yaml
      - sam deploy \
          --template-file packaged.yaml \
          --stack-name iw-demo-cfn \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
