version = 0.1

[default]
[default.build]
# Use container builds if you want parity with Lambda runtime
use_container = false

[default.package]
s3_bucket = "iw-demo-cfn-artifacts-us-east-1"
output_template_file = "packaged.yaml"

[default.deploy]
stack_name = "iw-demo-cfn"
s3_bucket = "iw-demo-cfn-artifacts-us-east-1"
s3_prefix = "graphql"
region = "us-east-1"
capabilities = "CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "PipelineBucketName=iw-demo-cfn-artifacts-us-east-1 AuroraSecretArn=arn:aws:secretsmanager:us-east-1:920671455518:secret:AuroraSecret-Egw1Zv"
